### PR TITLE
Cayenne-MQTT-Arduino adapted for Energia

### PR DESCRIPTION
**Pull request by rei-vilo**
Tested with 

* LaunchPad CC3200
* LaunchPad TM4C and CC3100 BoosterPack

Two examples 
* Basic `CC3200_Cayenne`
* Weather station `CC3200_Sensors_Cayenne` with Sensor BoosterPack

### CODE REVIEW

**Comment by rei-vilo** [comment]
## Warning

I've removed the examples for Arduino.

**Comment by asanchezdelc** [comment]
@rei-vilo Please could you put back the Arduino examples.

**Comment by rei-vilo** [comment]
Arduino examples back.

**Comment by jburhenn** [comment]
@rei-vilo Thanks for contributing. Can you please make a few other changes as well?

1. It looks like your pull request is a little behind. Please rebase with master.
2. Please put the WiFi & Cayenne credentials in the example sketches, near the top, instead of in their own header file so they are consistent with the Arduino examples.
3. Replace `BLYNK_NO_FLOAT` with `NO_FLOAT` in DetectDevice.h.

**Comment by rei-vilo** [comment]
> It looks like your pull request is a little behind. Please rebase with master.

How to rebase with the GitHub app, for macOS? I can perform it manually.

> Please put the WiFi & Cayenne credentials in the example sketches, near the top, instead of in their own header file so they are consistent with the Arduino examples. 

Done.

> Replace BLYNK_NO_FLOAT with NO_FLOAT in DetectDevice.h.

Done.

**Comment by jburhenn** [comment]
I haven't used GitHub for Mac so I'm not sure how it does rebasing. This link seems to suggest there is a Sync Branch command. That might be how it's done. If you can get it to sync with the upstream myDevicesIoT repo.
http://stackoverflow.com/questions/12576384/how-does-github-for-mac-synchronize

**Comment by jburhenn** [comment]
I tried using GitHub's "Rebase and merge" to handle the rebasing but it still seemed to get the old code. Looks like one of the commits may have re-added some old code. I'll just do some manual cleanup.

@rei-vilo You shouldn't need to look at rebasing anymore.

**Comment by rei-vilo** [comment]
New base fails to compile against the Arduino Zero and CC3200, among other boards.

The culprit comes from the removal of `CayenneValueArray`, which conflicts with the `F()` turn-around. Setting the macro `#define F(x) x` solved the problem.

I performed the rebase manually, added my code and tested it with Energia. Success!

**Comment by rei-vilo** [comment]
See #3

**Pull request merged**
